### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by KAMIENDER** [x00bence/lol-aram-boost#11]
![QQ图片20210608013604](https://user-images.githubusercontent.com/30643514/121064266-eb18fe80-c7f9-11eb-8b74-3246c534921f.png)
it does not work

**Comment by Yeagorn** [comment]
It doesn't work cause you don't have LoL open

**Comment by x00bence** [comment]
As mentioned above, you need to have League of Legends open before trying to run the script. You also need to run the script with the same privileges as your League of Legends.
