### ISSUE TITLE
Nothing happens when i run the script

### ISSUE THREAD

**Issue by adsadsadsadsa** [x00bence/lol-aram-boost#2]
Hey as the title says, when i run the script nothing happens, to be exact a blank cmd opens up then instantly dissapears , I have python that cant be the issue, could you maybe help me figure out the cause of this problem? (yes i tried to run it with administrator rights)
Thank you in advance

**Comment by x00bence** [comment]
Hey!

All good, but I'm going to need a bit more info. 

Which Python version are you running? You can check this via the `python --version` command in the command prompt. 

Do you have the `requests` module installed? This is a required dependency, you may install it via the `pip install requests` or `python -m pip install requests` command.

Please make sure you open the client before starting the script.

Thank you for the report, it's my bad for not including this information within the README.

**Comment by adsadsadsadsa** [comment]
Hey, the request module was the problem ,thank you for your assistance!
