### ISSUE TITLE
error when i run run.bat

### ISSUE THREAD

**Issue by gobelet69** [x00bence/lol-aram-boost#3]
Traceback (most recent call last):
  File "D:\Librairies\Desktop\lol-aram-boost-master\aram.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by x00bence** [comment]
Hey,

Duplicate issue; #2 

Please make sure you install the `requests` module which is a dependency required by lol-aram-boost. You can install via issuing either of the following commands in a separate command prompt: `pip install requests` or `python -m pip install requests`.
