### ISSUE TITLE
There is no issues 

### ISSUE THREAD

**Issue by gadayum** [x00bence/lol-aram-boost#4]
My dude , i wanna thank you for that alot , i just wanna ask about the ban rate , it safe to use for now right ?

**Comment by x00bence** [comment]
No problem! I hope you enjoy it! :)

**Ban rate:** probably close to 0%. 

Riot can start detecting the script but they are not doing that. I think its 99.9% safe to use. I have been using it every ARAM game for the last month and I'm not banned.

I heard they might patch this method in the next few patches though, so enjoy it while you can.
