### ISSUE TITLE
Doesn't work on Garena client.

### ISSUE THREAD

**Issue by RadioactivePeaches** [x00bence/lol-aram-boost#6]
title

**Comment by x00bence** [comment]
I'm not sure how the Garena client works exactly, are there any errors when you're running the script? You could also try running it as admin and see if it fixes anything.

**Comment by RadioactivePeaches** [comment]
Opens, says League client is open, but does nothing. It was run as admin.

**Comment by RadioactivePeaches** [comment]
Any way for me to get logs?

**Comment by x00bence** [comment]
Alright, and after pressing Enter, it says `[+] Boosted the lobby!`, correct?

I'm going to try and get my hands on a Garena client and see what I can do, although some other Garena users have told me that it works.
