### ISSUE TITLE
Semi working

### ISSUE THREAD

**Issue by alexandertt1** [x00bence/lol-aram-boost#9]
BE has been fixed. You gain nothing but the skins still work. Only tried on EUW so far maybe other servers still gains BE.

**Comment by x00bence** [comment]
I am aware of this issue. It seems like the BE still works on some servers, though. I can't really do anything about this issue, as this is all server-sided and controlled by Riot Games themselves.

**Comment by alexandertt1** [comment]
Hmm. Tried yesterday, got the skins got no BE. Tried today and got both skins and BE worked. Seems like RIot is messing around with some stuff.
